# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true

    # Note that the session will be started ONLY if you read or write from it.
    session: 
        cookie_lifetime: 3600 # Durée de vie du cookie de session en secondes (1 heure) 
        gc_maxlifetime: 3600 # Durée de vie maximale de la session en secondes (1 heure)

    #esi: true
    #fragments: true

when@test:
    framework:
        csrf_protection: true
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
